apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

# Replicas configuration for Dev environment
replicas:
  - name: adservice
    count: 1
  - name: cartservice
    count: 1
  - name: checkoutservice
    count: 1
  - name: currencyservice
    count: 1
  - name: emailservice
    count: 1
  - name: frontend
    count: 1
  - name: loadgenerator
    count: 1
  - name: paymentservice
    count: 1
  - name: productcatalogservice
    count: 1
  - name: recommendationservice
    count: 1
  - name: reviewsservice
    count: 1
  - name: shippingservice
    count: 1

patches:
  - target:
      kind: Service
      name: frontend-external
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30080

